version: '3'

tasks:
  clean:
    cmds:
      - docker run -e FLYWAY_PASSWORD={{.DATABASE_PASSWORD}} -e FLYWAY_URL=jdbc:postgresql://host.docker.internal:{{.DATABASE_PORT}}/{{.DATABASE_NAME}} -e FLYWAY_USER={{.DATABASE_USER}} --rm -v {{.PWD}}/flyway/sql:/flyway/sql flyway/flyway clean
    desc: Prints the details and status information about all the migrations.
    silent: true
    vars:
      PWD: $(pwd)

  info:
    cmds:
      - docker run -e FLYWAY_PASSWORD={{.DATABASE_PASSWORD}} -e FLYWAY_URL=jdbc:postgresql://host.docker.internal:{{.DATABASE_PORT}}/{{.DATABASE_NAME}} -e FLYWAY_USER={{.DATABASE_USER}} --rm -v {{.PWD}}/flyway/sql:/flyway/sql flyway/flyway info
    desc: Prints the details and status information about all the migrations.
    silent: true
    vars:
      PWD: $(pwd)

  migrate:
    cmds:
      - docker run -e FLYWAY_PASSWORD={{.DATABASE_PASSWORD}} -e FLYWAY_URL=jdbc:postgresql://host.docker.internal:{{.DATABASE_PORT}}/{{.DATABASE_NAME}} -e FLYWAY_USER={{.DATABASE_USER}} --rm -v {{.PWD}}/flyway/sql:/flyway/sql flyway/flyway migrate
    desc: Prints the details and status information about all the migrations.
    silent: true
    vars:
      PWD: $(pwd)
